#!/bin/bash

# Download, build and install latest stable Neovim release from sources

# Install build dependencies
echo ""
echo "-----------------------------"
echo "Installing build dependencies"
echo "-----------------------------"
sudo apt install \
    ninja-build gettext cmake unzip curl \  # build dependencies
    git xclip npm                           # extra dependencies

# Clone repo
echo ""
echo "--------------------------"
echo "Clonning Neovim repository"
echo "--------------------------"
if [ ! -d "neovim" ]; then
    git clone https://github.com/neovim/neovim
else
    cd neovim
    git pull
    cd ..
fi

# Checkout stable release
echo ""
echo "-----------------------"
echo "Checkout stable release"
echo "-----------------------"
cd neovim
git checkout stable

# Build
echo ""
echo "---------------"
echo "Building Neovim"
echo "---------------"
make CMAKE_BUILD_TYPE=Release
sudo make install
