name: default
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - jupyter
  - jupyterlab
  - nodejs # needed by jupyterlab
  - ipython
  - nbdime # git diffs for notebooks
  - livereload
  # Scientific stack
  - numpy
  - matplotlib
  - scipy
  - sympy
  - xarray
  - pandas
  - netcdf4
  # Linting and style checking
  - black
  - flake8
